Description: DynamoDB Stack Template - movies

Resources:
  MoviesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'movies'
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  MoviesTableArn:
    Description: "The ARN of the Movies table"
    Value: !GetAtt MoviesTable.Arn
  MoviesTableName:
    Description: "The Name of the Movies table"
    Value: !Ref MoviesTable