version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Configure AWS CLI...
      - aws configure set aws_access_key_id $AWS_CREDENTIALS_ACCESS_KEY
      - aws configure set aws_secret_access_key $AWS_CREDENTIALS_SECRET_KEY
      - aws configure set default.region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Building the app...
      - echo Execute AWS CLI commands...
      - ./initialized-params.sh