Description: Parameter Store Stack Template - movies

Resources:
  JwtConfigurationSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: jwtConfig
      Description: JWT configuration secret
      SecretString: 
        Fn::Sub: |
          {
            "secretKey": "",
            "expirationTime": ""
          }

  RemoteApiConfigurationSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: remoteApiConfig
      Description: Remote API configuration secret
      SecretString: 
        Fn::Sub: |
          {
            "apiUrl": "",
            "apiKey": "",
            "apiVersion": ""
          }

Outputs:
  JwtConfigurationSecretARN:
    Description: The ARN of the JWT configuration secret.
    Value: 
      Ref: JwtConfigurationSecret

  RemoteApiConfigurationSecretARN:
    Description: The ARN of the remote API configuration secret.
    Value: 
      Ref: RemoteApiConfigurationSecret