Description: ApiGetway Stack Template

Resources:
  MoviesHTTPApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: 'MoviesApiGetway'
      ProtocolType: 'HTTP'
      
Outputs:
  MoviesApiGetwayId:
    Description: "The ID of the MoviesApiGetway"
    Value: !Ref MoviesHTTPApi