Description: ApiGetway Stack Template

Resources:
  MoviesApiGetway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'MoviesApiGetway'

  MoviesResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MoviesApiGetway
      ParentId: !GetAtt 
        - MoviesApiGetway
        - RootResourceId
      PathPart: 'movies'
  
  UsersResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MoviesApiGetway
      ParentId: !GetAtt 
        - MoviesApiGetway
        - RootResourceId
      PathPart: 'users'
  
  MoviesGetMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: 'GET'
      ResourceId: !Ref MoviesResource
      RestApiId: !Ref MoviesApiGetway
      AuthorizationType: 'NONE'
      Integration:
        Type: 'MOCK'
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"message": "Mock integration in effect"}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
  
  UsersGetMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: 'GET'
      ResourceId: !Ref UsersResource
      RestApiId: !Ref MoviesApiGetway
      AuthorizationType: 'NONE'
      Integration:
        Type: 'MOCK'
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"message": "Mock integration in effect"}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
        
  GatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: 
      - MoviesGetMethod
      - UsersGetMethod
    Properties:
      RestApiId: !Ref MoviesApiGetway
      
  DevStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      StageName: 'dev'
      RestApiId: !Ref MoviesApiGetway
      DeploymentId: !Ref GatewayDeployment

Outputs:
  MoviesApiGetwayArn:
    Description: "The ARN of the MoviesApiGetway"
    Value: !Join
      - ""
      - - "arn:aws:execute-api:"
        - !Ref "AWS::Region"
        - ":"
        - !Ref "AWS::AccountId"
        - ":"
        - !Ref MoviesApiGetway
